import React,{act,useRef} from 'react';import {createRoot} from 'react-dom/client';
import StudentsPage from '/src/pages/StudentsPage.jsx';import SectionsPage from '/src/pages/SectionsPage.jsx';import SchedulesPage from '/src/pages/SchedulesPage.jsx';import {usePrintReadiness} from '/src/hooks/usePrintReadiness.js';
window.IS_REACT_ACT_ENVIRONMENT=true;const host=document.getElementById('test-root');const root=createRoot(host);const results=document.getElementById('results');
const assert=(condition,message)=>{if(!condition)throw Error(message)};const render=async node=>{await act(async()=>root.render(node))};
const button=name=>[...host.querySelectorAll('button')].find(n=>n.textContent.trim()===name);
const input=label=>{const l=[...host.querySelectorAll('label')].find(n=>n.textContent===label);return document.getElementById(l?.htmlFor)};
const click=async node=>{assert(node,'button absent');await act(async()=>node.click())};
const scenario=async name=>{await act(async()=>{window.previewScenario=name;window.dispatchEvent(new Event('preview-change'))})};
const fill=async(node,value)=>{assert(node,'input absent');await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}))})};
async function draftTest(Page,add,label){await scenario('normal');await render(<Page schoolYear="2026-2027"/>);await click(button(add));await fill(input(label),'Retain this draft');await scenario('error');assert(host.querySelector('dialog[open]'),'Open draft dialog disappeared during resource error');assert(input(label).value==='Retain this draft','Draft lost during error');assert([...host.querySelectorAll('dialog button')].filter(n=>n.textContent.includes(add)).every(n=>n.matches(':disabled')),'Save remains enabled during error');await scenario('normal');assert(input(label).value==='Retain this draft','Draft lost after recovery');}
function PrintCase({show}){const ref=useRef(null);const ready=usePrintReadiness(ref,'same-key',1);return <><output data-ready>{String(ready)}</output>{show&&<div ref={ref}><img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'%3E%3C/svg%3E"/></div>}</>}
const tests=[['Section details have a keyboard button',async()=>{await scenario('normal');await render(<SectionsPage schoolYear="2026-2027"/>);const control=host.querySelector('button[aria-label="View Acacia section details"]');assert(control,'Section detail button absent');await click(control);assert(host.querySelector('dialog[open]'),'Section details did not open');}],['Learner draft survives retrieval failure',()=>draftTest(StudentsPage,'Add learner','Last name')],['Section draft survives retrieval failure',()=>draftTest(SectionsPage,'Add section','Section name')],['Schedule draft survives retrieval failure',()=>draftTest(SchedulesPage,'Add schedule','Schedule name')],['Print readiness resets when QR root detaches',async()=>{await render(<PrintCase show/>);await act(async()=>new Promise(r=>setTimeout(r,80)));assert(host.querySelector('[data-ready]').textContent==='true','Initial QR never became ready');await render(<PrintCase show={false}/>);assert(host.querySelector('[data-ready]').textContent==='false','Detached QR root still reports ready');await render(<PrintCase show/>);await act(async()=>new Promise(r=>setTimeout(r,80)));assert(host.querySelector('[data-ready]').textContent==='true','Remounted QR root never became ready');}]];
for(const[name,test]of tests){try{await test();results.append(Object.assign(document.createElement('p'),{textContent:'PASS '+name}));}catch(e){results.append(Object.assign(document.createElement('p'),{textContent:'FAIL '+name+': '+e.message}));}finally{await render(null);}}
results.dataset.done='true';
