// Every user-visible string of the parent portal. Translation later is a
// content change to this file only. Test enforces: no empty values, no
// "location" / "tracking" / "live" wording (spec §7).
export const FORBIDDEN = ['location', 'tracking', 'live'];

const S = {
  appName: "BNHS Learner's Attendance",
  tagline: 'For parents and guardians of BNHS learners.',
  signInGoogle: 'Sign in with Google',
  signInEmail: 'Sign in with email',
  createAccount: 'Create an account',
  forgotPassword: 'Forgot password?',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signOut: 'Sign out',
  back: 'Back',
  continue: 'Continue',
  cancel: 'Cancel',
  send: 'Send',
  loading: 'Loading…',
  offlineBanner: 'You are offline. Showing what was last loaded.',
  lastUpdated: 'Last updated',
  authError: 'That email and password did not match.',
  createError: 'Could not create the account. Check the email and choose a password of at least 8 characters.',
  resetSent: 'A password reset email was sent if that address has an account.',
  verifyTitle: 'Verify your email',
  verifyBody: 'Check your email for a verification message, then tap Continue.',
  verifyResend: 'Send the email again',
  verifyNotYet: 'Not verified yet. Open the email and tap the link, then try again.',
  consentTitle: 'How the school uses your information',
  consentBody1: 'This portal shows you the gate scans the school kiosk recorded for the learner(s) linked to you: the time your learner scanned in and out at the school gate.',
  consentBody2: 'The school records your name, email, relationship to the learner, and the devices you turn notifications on for. It keeps gate scan records for the current and previous school year, then deletes them.',
  consentBody3: 'You can turn notifications off, report a record you think is wrong, or delete your account at any time from Settings. Questions go to the school registrar or the school\'s privacy focal person.',
  consentCheckbox: 'I have read this notice and agree.',
  consentLink: 'Read the full privacy notice',
  activateTitle: 'Link your learner',
  activateBody: 'Enter the activation code printed on the slip from the school.',
  activateCodeLabel: 'Activation code',
  activateRelationship: 'Your relationship to the learner',
  activateButton: 'Link learner',
  activateSuccess: 'Linked! You can now see gate scans for',
  activateFailed: 'That code could not be used. Ask the registrar to reissue your slip.',
  activateNoSlip: 'No slip? Ask the school for access',
  activateAnother: 'Link another learner',
  homeNoLinks: 'No learners linked yet.',
  homeTodayNone: 'No entry recorded today',
  homeEntered: 'Entered',
  homeLeft: 'Left',
  homeViewHistory: 'View history',
  notifBannerTitle: 'Get a notification for new gate scans',
  notifBannerButton: 'Turn on notifications',
  historyTitle: 'Gate scans',
  historyEmpty: 'No gate scans recorded yet.',
  historyLoadOlder: 'Load older scans',
  eventIn: 'Entered school',
  eventOut: 'Left school',
  eventVoided: 'Corrected by the school',
  eventLate: 'Recorded late',
  eventManual: 'Added by the school',
  reportThis: 'Report this record',
  inboxTitle: 'Inbox',
  inboxEmpty: 'Nothing here yet. New gate scans and messages from the school appear here.',
  inboxNewEvent: 'New gate scan',
  inboxFromSchool: 'From the school',
  dayToday: 'Today',
  dayYesterday: 'Yesterday',
  inboxError: 'Could not load your inbox right now. Please try again in a moment.',
  reportTitle: 'Report a record',
  reportReason: 'What seems wrong?',
  reportReasonWrongTime: 'The time is wrong',
  reportReasonNotThisLearner: 'This scan was not my learner',
  reportReasonMissing: 'A scan is missing',
  reportReasonOther: 'Something else',
  reportMessage: 'Tell the registrar more (optional)',
  reportSent: 'Sent to the registrar. You will get a message here when it is reviewed.',
  reportFailed: 'Could not send the report right now. Please try again.',
  requestTitle: 'Ask the school for access',
  requestBody: 'Use this only if you did not receive an activation slip. The registrar will check your request.',
  requestLrn: 'Learner\'s LRN (12 digits)',
  requestName: 'Learner\'s full name',
  requestContact: 'Your contact number',
  requestMessage: 'Message (optional)',
  requestSent: 'Request sent. The registrar will review it.',
  requestOpen: 'Waiting for the registrar',
  requestApproved: 'Approved',
  requestDenied: 'Not approved',
  settingsTitle: 'Settings',
  settingsNotifications: 'Notifications',
  settingsAccountToggle: 'Send me a notification for new gate scans',
  settingsThisDevice: 'This device',
  notifOn: 'On for this device',
  notifOff: 'Off for this device',
  notifBlocked: 'Blocked in your browser settings',
  notifBlockedHelp: 'Open your browser\'s site settings for this page and allow Notifications, then return here.',
  notifUnsupported: 'Notifications are not available in this browser.',
  notifIosInstall: 'On iPhone or iPad, first add this page to your Home Screen (Share → Add to Home Screen), then open it from there.',
  notifTurnOn: 'Turn on for this device',
  notifTurnOff: 'Turn off for this device',
  pushDisclaimer: 'Notifications may be delayed or missed. Your Inbox always has the complete record.',
  settingsLearners: 'Linked learners',
  settingsRemoveHint: 'To remove a learner, ask the school registrar.',
  settingsReports: 'My reports',
  settingsRequests: 'My access requests',
  settingsPrivacy: 'Privacy notice',
  settingsDelete: 'Delete my account',
  settingsDeleteConfirm: 'This removes your account, your notification devices, and your inbox. Gate scan records stay with the school. Continue?',
  settingsDeleteButton: 'Yes, delete my account',
  pausedBanner: 'Notifications are paused by the school',
  accessEnded: 'Your access to this learner has ended. Contact the registrar.',
  navHome: 'Home',
  navInbox: 'Inbox',
  navSettings: 'Settings',
  notFound: 'That page does not exist.',
};
export default S;
